version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
        - BetterAuth
        - BetterAuthEmailPassword
        - BetterAuthUsername
        - BetterAuthAnonymous
        - BetterAuthSocialOAuth
        - BetterAuthAppleSignIn
        - BetterAuthMagicLink
        - BetterAuthSwiftUI
        - BetterAuthOrganization
